export const SUPABASE_URL = 'https://nchcdxrbfoshfipbyjag.supabase.co';
export const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jaGNkeHJiZm9zaGZpcGJ5amFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzE3MDYsImV4cCI6MjA2NTU0NzcwNn0.zrrU6WQ-IGdtHAzSBrboBNSV_Y3ZJoMlRPrEqfajXLw';
